### PR TITLE
Aswanth

### PR DESCRIPTION
**Pull request by Aswanth-Ramamoorthy**
Check the user_details function and some sub-functions.

### CODE REVIEW

**Review by somasundaramravindra — APPROVED** [review]
works fine for me

**Review by priyangasoundararaja — APPROVED** [review]
Checked your code. Works fine

**Review by priyangasoundararaja — APPROVED** [review]
Checked your code. Works fine

**Review by vigneshbalaj — APPROVED** [review]
Checked the functionality of the code and its can be move to Dev branch.

**Review by vigneshbalaj — APPROVED** [review]
Checked the functionality of the code and it can be move to Dev branch.

**Pull request merged**
