### PR TITLE
Soma

### PR DESCRIPTION
**Pull request by somasundaramravindra**
cast_vote function for development

### CODE REVIEW

**Review by Aswanth-Ramamoorthy — APPROVED** [review]
It's good and works perfectly for me

**Review by priyangasoundararaja — APPROVED** [review]
Checked your code. Works fine

**Review by vigneshbalaj — APPROVED** [review]
Checked the functionality of the code and its can be move to Dev branch.

**Review by priyangasoundararaja — APPROVED** [review]
Checked your code. Works fine

**Review by vigneshbalaj — APPROVED** [review]
Checked the functionality of the code and it can be move to Dev branch.

**Pull request merged**
